version: 2
# updates:
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "daily"
#   - package-ecosystem: "npm"
#     directory: "/services/frontend"
#     schedule:
#       interval: "daily"
#   - package-ecosystem: "gomod"
#     directory: "/services/api"
#     schedule:
#       interval: "daily"