apiVersion: v2
name: dependency
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: argo-cd
    repository: https://charts.bitnami.com/bitnami
    condition: argo-cd.enabled
    version: 4.7.19

  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    version: 12.8.0

  - name: kratos
    repository: https://k8s.ory.sh/helm/charts
    condition: kratos.enabled
    version: 0.35.0

  - name: minio
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
    version: 12.6.12

  - name: zitadel
    repository: https://charts.zitadel.com
    condition: zitadel.enabled
    version: 5.0.0
