argo-cd:
  enabled: true

traefik:
  enabled: true

cockroach:
  enabled: true

zitadel:  
  masterkey: 'MasterkeyNeedsToHave32Characters'

  secretConfig:

    Database:
      cockroach:
        User:
          # If the user doesn't exist already, it is created
          Username: 'zitadel_user'
          Password: 'Secret_DB_User_Password'
        Admin:
          Username: 'root'
          Password: ''

  configmapConfig:
    Log:
      Level: 'info'

    # Make ZITADEL accessible over HTTP, not HTTPS
    ExternalSecure: false
    ExternalDomain: localhost

    # the configmap is also passed to the zitadel binary via the --steps flag
    FirstInstance:
      Org:
        Human:
          # use the loginname root@zitadel.localhost
          Username: 'root'
          Password: 'RootPassword1!'

minio:
  enabled: true