argo-cd:
  enabled: false

postgresql:
  enabled: true
  postgresPassword: root
  auth:
    username: admin
    password: admin
  databases:
    - name: base
    - name: auth
  
minio:
  enabled: false
  auth:
    rootUser: admin
    rootPassword: password

kratos:
  enabled: false