argo-cd:
  enabled: false

postgresql:
  enabled: false
  postgresPassword: root
  auth:
    username: admin
    password: admin
  databases:
    - name: base
    - name: auth

minio:
  enabled: false

  auth:
    rootUser: admin
    rootPassword: password

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "minio.lab.org"
  
  apiIngress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "file.lab.org"

kratos:
  enabled: false