argo-cd:
  enabled: false

cockroachdb:
  enabled: false

minio:
  enabled: false

  auth:
    rootUser: admin
    rootPassword: password

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "minio.lab.org"
  
  apiIngress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "file.lab.org"

kratos:
  enabled: false