name: Build and Push Golang Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER: "${{ github.repository_owner }}"

jobs:
  build:
    strategy:
      matrix:
        services: ["backend"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Build ${{ matrix.services }} service
        working-directory: services/${{ matrix.services }}
        run: go build -o ${{ matrix.services }}

      - name: Extract image metadata for ${{ matrix.services }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.services }}

      - name: Build and push ${{ matrix.services }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.services }}
          file: services/${{ matrix.services }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
