name: Build and Push Golang Docker Images
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER: "${{ github.repository_owner }}"

jobs:
  build:
    strategy:
      matrix:
        services: ["backend"]

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Step 3: Build the Golang application
      - name: Build Golang application
        working-directory: "${{ matrix.services }}"
        run: go build -o app

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GH_TOKEN }}"

      # Step 5: Build Docker image and push to GitHub Container Registry
      - name: "Build and push ${{ matrix.services }}"
        uses: docker/build-push-action@v4
        with:
          context: "${{ matrix.services }}"
          file: "services/${{ matrix.services }}/Dockerfile"
          push: true
          tags: >-
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.services }}:${{ github.sha }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
