name: Build and Push Golang Docker Images

on:
  push:
    paths:
      - 'services/**'
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER: "${{ github.repository_owner }}"

jobs:
  build:
    strategy:
      matrix:
        services: ["todo"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Build ${{ matrix.services }} service
        working-directory: services/${{ matrix.services }}
        run: go build -o ${{ matrix.services }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
    
      - name: Build and push ${{ matrix.services }}
        uses: docker/build-push-action@v5
        with:
          context: "services/${{ matrix.services }}"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/base/${{ matrix.services }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}